# Specify our compose version
version: '3'

# Container services
services:
  # Specify notebook service
  notebook:
    # Select image to be used for container
    build:
      context: ./docker
      dockerfile: Dockerfile
    # Mount internal folder to /notebooks folder in container, 1:1 copy
    volumes:
     - ./src/:/notebooks

     # Map an internal drive/folder to the insides of the containmer
     - I:/output:/notebooks/output
    
    # Place specific OS variables here
    environment:
      - JUPYTER_ENABLE_LAB=yes
    env_file:
      - .env
    # Run this command on container startup: Start notebook service
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks

    # Specify container name
    container_name: notebooks

    # Mount external port to an interal port EXTERNAL:INTERNAL
    ports:
      - "8888:8888"


