version: '3'
services:
  notebook:
    image: zehnder/notebook:1.0
    volumes:
     - ./src/:/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.notebook_dir=/notebooks
    container_name: lab
    ports:
      - "8888:8888"